import os

class Config:
    CONFLUENCE_BASE_URL = os.getenv("CONFLUENCE_BASE_URL")
    CONFLUENCE_USERNAME = os.getenv("CONFLUENCE_USERNAME")
    CONFLUENCE_API_TOKEN = os.getenv("CONFLUENCE_API_TOKEN")
    SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
    SLACK_VERIFICATION_TOKEN = os.getenv("SLACK_VERIFICATION_TOKEN")
    SLACK_RESPONSE_URL = os.getenv("SLACK_RESPONSE_URL")
    MODEL_NAME = 'all-MiniLM-L6-v2'
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
  
