import os

class Config:
    CONFLUENCE_BASE_URL = os.getenv("CONFLUENCE_BASE_URL")
    CONFLUENCE_USERNAME = os.getenv("CONFLUENCE_USERNAME")
    CONFLUENCE_API_TOKEN = os.getenv("CONFLUENCE_API_TOKEN")
    SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
    SLACK_VERIFICATION_TOKEN = os.getenv("SLACK_VERIFICATION_TOKEN")
    SLACK_RESPONSE_URL = os.getenv("SLACK_RESPONSE_URL")
    MODEL_NAME = 'all-MiniLM-L6-v2'
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    ALERT_CHANNEL_ID = os.getenv("ALERT_CHANNEL_ID")
    SOCKET_TOKEN = os.getenv("SOCKET_TOKEN")
    SIGNING_SECRET = os.getenv("SIGNING_SECRET")
    TESTING = os.getenv("TESTING")
    CONFLUENCE_PAGE_ID: str = os.getenv("CONFLUENCE_PAGE_ID")
    BOT_ID = os.getenv("BOT_ID")
  
